### ISSUE TITLE
About the layers to keep fixed when fine-tuning?

### ISSUE THREAD

**Issue by nnop** [tianzhi0549/py-faster-rcnn-resnet-imagenet#1]
From the [ResNet-101 proto file](https://github.com/tianzhi0549/py-faster-rcnn-resnet-imagenet/blob/master/models/imagenet/ResNet-101/faster_rcnn_alt_opt/stage1_rpn_train.pt), I notice that you keep the parameters fixed before `conv4_x` when training Faster-RCNN.
Is this also what the authors did? I didn't find relative description in the original [ResNet paper](https://arxiv.org/abs/1512.03385). 

The [VGG16 model](https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/VGG16/faster_rcnn_alt_opt/stage1_rpn_train.pt) of the original Faster-RCNN implementation freeze the layers before `conv3_x`, which is also how the authors done in [R-FCN](https://github.com/daijifeng001/R-FCN/blob/master/models/rfcn_prototxts/ResNet-101L_res3a/train_val.prototxt).

It's interesting to evaluate about the affect of different number of layers to freeze for fine tuning.

**Comment by tianzhi0549** [comment]
I do not know whether or not the original ResNet fixes these layers. I just followed a best practice.
Evaluating the difference is of interest. And the authors of Fast RCNN did the comparison for VGG16. You can find it in Section 4.5 of Fast CNN paper. Thank you:-).
